// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SNRMS.Core.Data;

#nullable disable

namespace SNRMS.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406030409_AddEmployeeIdToInstructor")]
    partial class AddEmployeeIdToInstructor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SNRMS.Core.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.HasIndex("SectionId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("HospitalId");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("SNRMS.Core.Models.RotationAssignment", b =>
                {
                    b.Property<int>("RotationAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RotationAssignmentId"));

                    b.Property<string>("DaySlot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("RotationAssignmentId");

                    b.HasIndex("GroupId");

                    b.HasIndex("StationId");

                    b.ToTable("RotationAssignments");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("SectionId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StationId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StationId");

                    b.HasIndex("HospitalId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StudentId");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SNRMS.Core.Models.StudentRotationHistory", b =>
                {
                    b.Property<int>("StudentRotationHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StudentRotationHistoryId"));

                    b.Property<int>("RotationAssignmentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("StudentRotationHistoryId");

                    b.HasIndex("RotationAssignmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentRotationHistories");
                });

            modelBuilder.Entity("SNRMS.Core.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            IsActive = true,
                            PasswordHash = "$2a$11$p.RbB5OBg.kXYcgRKa8zNenEBkCG8zzD2gthQflabRIZHee3IikMC",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SNRMS.Core.Models.Group", b =>
                {
                    b.HasOne("SNRMS.Core.Models.Section", "Section")
                        .WithMany("Groups")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SNRMS.Core.Models.RotationAssignment", b =>
                {
                    b.HasOne("SNRMS.Core.Models.Group", "Group")
                        .WithMany("RotationAssignments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SNRMS.Core.Models.Station", "Station")
                        .WithMany("RotationAssignments")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Section", b =>
                {
                    b.HasOne("SNRMS.Core.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Station", b =>
                {
                    b.HasOne("SNRMS.Core.Models.Hospital", "Hospital")
                        .WithMany("Stations")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Student", b =>
                {
                    b.HasOne("SNRMS.Core.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SNRMS.Core.Models.StudentRotationHistory", b =>
                {
                    b.HasOne("SNRMS.Core.Models.RotationAssignment", "RotationAssignment")
                        .WithMany("RotationHistories")
                        .HasForeignKey("RotationAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SNRMS.Core.Models.Student", "Student")
                        .WithMany("RotationHistory")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RotationAssignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SNRMS.Core.Models.User", b =>
                {
                    b.HasOne("SNRMS.Core.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId");

                    b.HasOne("SNRMS.Core.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Instructor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Group", b =>
                {
                    b.Navigation("RotationAssignments");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Hospital", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("SNRMS.Core.Models.RotationAssignment", b =>
                {
                    b.Navigation("RotationHistories");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Section", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Station", b =>
                {
                    b.Navigation("RotationAssignments");
                });

            modelBuilder.Entity("SNRMS.Core.Models.Student", b =>
                {
                    b.Navigation("RotationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
